'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'az' | 'en' | 'ru'

type Translations = {
  [key: string]: string
}

export const translations: Record<Language, Translations> = {
  az: {
    // Header
    search: 'Axtar...',
    favorites: 'Sevimlilər',
    cart: 'Səbət',
    account: 'Hesab',
    login: 'Giriş',
    register: 'Qeydiyyat',
    logout: 'Çıxış',
    // Nav categories
    hairCare: 'Saç Baxımı',
    nailCare: 'Dırnak Baxımı',
    cosmetologyDevices: 'Kosmetoloji Cihazlar',
    makeup: 'Makiyaj',
    faceCare: 'Üz Baxımı',
    laserEquipment: 'Lazer Avadanlıqları',
    professionalTools: 'Peşəkar Alətlər',
    // Sub-categories Hair
    hairTreatment: 'Saç Müalicəsi',
    hairColoring: 'Saç Boyası',
    keratin: 'Keratin',
    bioPerm: 'Bio Zavivka',
    // Sub-categories Nail
    gelPolish: 'Gel Lak',
    regularPolish: 'Adi Lak',
    shellac: 'Shellac',
    nailDevices: 'Dırnak Cihazları',
    nailStickers: 'Dırnak Stikerleri',
    nailAccessories: 'Dırnak Aksesuarları',
    // Sub-categories Cosmetology
    facialMachines: 'Üz Aparatları',
    skincareEquipment: 'Peşəkar Dəri Baxımı',
    beautyDevices: 'Gözəllik Cihazları',
    // Sub-categories Makeup
    makeupTools: 'Peşəkar Alətlər',
    makeupProducts: 'Makiyaj Məhsulları',
    // Sub-categories Face Care
    serums: 'Serumlar',
    creams: 'Kremler',
    masks: 'Masklar',
    skincaresets: 'Dəri Baxım Setləri',
    // Sub-categories Laser
    laserDevices: 'Lazer Cihazları',
    laserAccessories: 'Lazer Aksesuarları',
    // Sub-categories Professional
    salonEquipment: 'Salon Avadanlıqları',
    sterilization: 'Sterilizasiya Alətləri',
    instruments: 'Peşəkar Alətlər',
    // Homepage
    heroTitle: 'Gözəlliyin\nSənəti',
    heroSubtitle: 'Premium gözəllik məhsulları və peşəkar salon ləvazimatları',
    shopNow: 'İndi Alış-veriş Et',
    discoverCollection: 'Kolleksiyanı Kəşf Et',
    featuredProducts: 'Seçilmiş Məhsullar',
    newArrivals: 'Yeni Gələnlər',
    bestSellers: 'Ən Çox Satılanlar',
    viewAll: 'Hamısına Bax',
    ourCategories: 'Kateqoriyalarımız',
    luxuryBeauty: 'Lüks Gözəllik',
    // Product
    addToCart: 'Səbətə Əlavə Et',
    addToFavorites: 'Sevimlilərə Əlavə Et',
    removeFromFavorites: 'Sevimlilərdən Çıxar',
    inStock: 'Stokda var',
    outOfStock: 'Stok yoxdur',
    quantity: 'Miqdar',
    description: 'Təsvir',
    specifications: 'Xüsusiyyətlər',
    relatedProducts: 'Əlaqəli Məhsullar',
    price: 'Qiymət',
    // Cart
    yourCart: 'Səbətiniz',
    emptyCart: 'Səbətiniz boşdur',
    continueShopping: 'Alış-verişə davam et',
    subtotal: 'Ara cəm',
    total: 'Cəmi',
    checkout: 'Ödəniş',
    remove: 'Sil',
    // Favorites
    yourFavorites: 'Sevimliləriniz',
    emptyFavorites: 'Siyahı boşdur',
    // Auth
    email: 'E-poçt',
    password: 'Şifrə',
    confirmPassword: 'Şifrəni Təsdiqlə',
    firstName: 'Ad',
    lastName: 'Soyad',
    phone: 'Telefon',
    loginTitle: 'Xoş Gəldiniz',
    registerTitle: 'Hesab Yaradın',
    dontHaveAccount: 'Hesabınız yoxdur?',
    alreadyHaveAccount: 'Artıq hesabınız var?',
    forgotPassword: 'Şifrəni unutdum',
    // Profile
    myProfile: 'Profilim',
    myOrders: 'Sifarişlərim',
    myAddresses: 'Ünvanlarım',
    paymentMethods: 'Ödəniş Üsulları',
    editProfile: 'Profili Redaktə Et',
    saveChanges: 'Dəyişiklikləri Saxla',
    address: 'Ünvan',
    city: 'Şəhər',
    country: 'Ölkə',
    // Checkout
    shippingInfo: 'Çatdırılma Məlumatları',
    paymentMethod: 'Ödəniş Üsulu',
    orderSummary: 'Sifariş Xülasəsi',
    placeOrder: 'Sifarişi Tamamla',
    creditCard: 'Kredit Kartı',
    cashOnDelivery: 'Çatdırılmada Ödəniş',
    cardNumber: 'Kart Nömrəsi',
    expiryDate: 'Son İstifadə Tarixi',
    cvv: 'CVV',
    orderSuccess: 'Sifarişiniz qəbul edildi!',
    // Footer
    aboutUs: 'Haqqımızda',
    contact: 'Əlaqə',
    privacyPolicy: 'Məxfilik Siyasəti',
    termsConditions: 'İstifadə Şərtləri',
    followUs: 'Bizi izləyin',
    newsletter: 'Xəbər Bülleteni',
    newsletterText: 'Yeni məhsullar və xüsusi təkliflər üçün abunə olun',
    subscribe: 'Abunə Ol',
    allRightsReserved: 'Bütün hüquqlar qorunur',
    shipping: 'Pulsuz çatdırılma',
    shippingDesc: '50 AZN üzəri sifarişlərə',
    returns: 'Asan İadə',
    returnsDesc: '30 gün ərzində',
    support: 'Dəstək',
    supportDesc: '7/24 xidmət',
    // Banners
    exclusiveOffer: 'Eksklüziv Təklif',
    limitedTime: 'Məhdud müddətli',
    shopCollection: 'Kolleksiyaya Bax',
  },
  en: {
    search: 'Search...',
    favorites: 'Favorites',
    cart: 'Cart',
    account: 'Account',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    hairCare: 'Hair Care',
    nailCare: 'Nail Care',
    cosmetologyDevices: 'Cosmetology Devices',
    makeup: 'Makeup',
    faceCare: 'Face Care',
    laserEquipment: 'Laser Equipment',
    professionalTools: 'Professional Tools',
    hairTreatment: 'Hair Treatment',
    hairColoring: 'Hair Coloring',
    keratin: 'Keratin',
    bioPerm: 'Bio Perm',
    gelPolish: 'Gel Polish',
    regularPolish: 'Regular Nail Polish',
    shellac: 'Shellac',
    nailDevices: 'Nail Devices',
    nailStickers: 'Nail Stickers',
    nailAccessories: 'Nail Accessories',
    facialMachines: 'Facial Machines',
    skincareEquipment: 'Professional Skincare Equipment',
    beautyDevices: 'Beauty Devices',
    makeupTools: 'Professional Makeup Tools',
    makeupProducts: 'Makeup Products',
    serums: 'Serums',
    creams: 'Creams',
    masks: 'Masks',
    skincaresets: 'Skincare Sets',
    laserDevices: 'Laser Devices',
    laserAccessories: 'Laser Accessories',
    salonEquipment: 'Salon Equipment',
    sterilization: 'Sterilization Tools',
    instruments: 'Beauty Professional Instruments',
    heroTitle: 'The Art of\nBeauty',
    heroSubtitle: 'Premium beauty products and professional salon supplies',
    shopNow: 'Shop Now',
    discoverCollection: 'Discover Collection',
    featuredProducts: 'Featured Products',
    newArrivals: 'New Arrivals',
    bestSellers: 'Best Sellers',
    viewAll: 'View All',
    ourCategories: 'Our Categories',
    luxuryBeauty: 'Luxury Beauty',
    addToCart: 'Add to Cart',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    quantity: 'Quantity',
    description: 'Description',
    specifications: 'Specifications',
    relatedProducts: 'Related Products',
    price: 'Price',
    yourCart: 'Your Cart',
    emptyCart: 'Your cart is empty',
    continueShopping: 'Continue Shopping',
    subtotal: 'Subtotal',
    total: 'Total',
    checkout: 'Checkout',
    remove: 'Remove',
    yourFavorites: 'Your Favorites',
    emptyFavorites: 'Your favorites list is empty',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    loginTitle: 'Welcome Back',
    registerTitle: 'Create Account',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    forgotPassword: 'Forgot Password',
    myProfile: 'My Profile',
    myOrders: 'My Orders',
    myAddresses: 'My Addresses',
    paymentMethods: 'Payment Methods',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    address: 'Address',
    city: 'City',
    country: 'Country',
    shippingInfo: 'Shipping Information',
    paymentMethod: 'Payment Method',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    creditCard: 'Credit Card',
    cashOnDelivery: 'Cash on Delivery',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    orderSuccess: 'Your order has been placed!',
    aboutUs: 'About Us',
    contact: 'Contact',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    followUs: 'Follow Us',
    newsletter: 'Newsletter',
    newsletterText: 'Subscribe for new products and exclusive offers',
    subscribe: 'Subscribe',
    allRightsReserved: 'All rights reserved',
    shipping: 'Free Shipping',
    shippingDesc: 'On orders over 50 AZN',
    returns: 'Easy Returns',
    returnsDesc: 'Within 30 days',
    support: 'Support',
    supportDesc: '24/7 service',
    exclusiveOffer: 'Exclusive Offer',
    limitedTime: 'Limited time',
    shopCollection: 'Shop Collection',
  },
  ru: {
    search: 'Поиск...',
    favorites: 'Избранное',
    cart: 'Корзина',
    account: 'Аккаунт',
    login: 'Войти',
    register: 'Регистрация',
    logout: 'Выйти',
    hairCare: 'Уход за волосами',
    nailCare: 'Уход за ногтями',
    cosmetologyDevices: 'Косметологические аппараты',
    makeup: 'Макияж',
    faceCare: 'Уход за лицом',
    laserEquipment: 'Лазерное оборудование',
    professionalTools: 'Профессиональные инструменты',
    hairTreatment: 'Лечение волос',
    hairColoring: 'Окрашивание волос',
    keratin: 'Кератин',
    bioPerm: 'Биозавивка',
    gelPolish: 'Гель-лак',
    regularPolish: 'Обычный лак',
    shellac: 'Шеллак',
    nailDevices: 'Аппараты для ногтей',
    nailStickers: 'Наклейки для ногтей',
    nailAccessories: 'Аксессуары для ногтей',
    facialMachines: 'Аппараты для лица',
    skincareEquipment: 'Профессиональный уход за кожей',
    beautyDevices: 'Аппараты для красоты',
    makeupTools: 'Профессиональные инструменты',
    makeupProducts: 'Продукты для макияжа',
    serums: 'Сыворотки',
    creams: 'Кремы',
    masks: 'Маски',
    skincaresets: 'Наборы по уходу за кожей',
    laserDevices: 'Лазерные аппараты',
    laserAccessories: 'Лазерные аксессуары',
    salonEquipment: 'Оборудование для салона',
    sterilization: 'Инструменты стерилизации',
    instruments: 'Профессиональные инструменты',
    heroTitle: 'Искусство\nКрасоты',
    heroSubtitle: 'Премиальные косметические товары и профессиональные салонные принадлежности',
    shopNow: 'Купить сейчас',
    discoverCollection: 'Открыть коллекцию',
    featuredProducts: 'Избранные товары',
    newArrivals: 'Новинки',
    bestSellers: 'Бестселлеры',
    viewAll: 'Посмотреть все',
    ourCategories: 'Наши категории',
    luxuryBeauty: 'Роскошная красота',
    addToCart: 'В корзину',
    addToFavorites: 'В избранное',
    removeFromFavorites: 'Убрать из избранного',
    inStock: 'В наличии',
    outOfStock: 'Нет в наличии',
    quantity: 'Количество',
    description: 'Описание',
    specifications: 'Характеристики',
    relatedProducts: 'Похожие товары',
    price: 'Цена',
    yourCart: 'Ваша корзина',
    emptyCart: 'Ваша корзина пуста',
    continueShopping: 'Продолжить покупки',
    subtotal: 'Промежуточный итог',
    total: 'Итого',
    checkout: 'Оформить заказ',
    remove: 'Удалить',
    yourFavorites: 'Ваше избранное',
    emptyFavorites: 'Список избранного пуст',
    email: 'Электронная почта',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    phone: 'Телефон',
    loginTitle: 'Добро пожаловать',
    registerTitle: 'Создать аккаунт',
    dontHaveAccount: 'Нет аккаунта?',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    forgotPassword: 'Забыли пароль',
    myProfile: 'Мой профиль',
    myOrders: 'Мои заказы',
    myAddresses: 'Мои адреса',
    paymentMethods: 'Способы оплаты',
    editProfile: 'Редактировать профиль',
    saveChanges: 'Сохранить изменения',
    address: 'Адрес',
    city: 'Город',
    country: 'Страна',
    shippingInfo: 'Информация о доставке',
    paymentMethod: 'Способ оплаты',
    orderSummary: 'Сводка заказа',
    placeOrder: 'Разместить заказ',
    creditCard: 'Кредитная карта',
    cashOnDelivery: 'Оплата при получении',
    cardNumber: 'Номер карты',
    expiryDate: 'Срок действия',
    cvv: 'CVV',
    orderSuccess: 'Ваш заказ размещён!',
    aboutUs: 'О нас',
    contact: 'Контакт',
    privacyPolicy: 'Политика конфиденциальности',
    termsConditions: 'Условия использования',
    followUs: 'Следите за нами',
    newsletter: 'Новостная рассылка',
    newsletterText: 'Подпишитесь на новые товары и эксклюзивные предложения',
    subscribe: 'Подписаться',
    allRightsReserved: 'Все права защищены',
    shipping: 'Бесплатная доставка',
    shippingDesc: 'При заказе от 50 AZN',
    returns: 'Лёгкий возврат',
    returnsDesc: 'В течение 30 дней',
    support: 'Поддержка',
    supportDesc: 'Служба 24/7',
    exclusiveOffer: 'Эксклюзивное предложение',
    limitedTime: 'Ограниченное время',
    shopCollection: 'К коллекции',
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'az',
  setLanguage: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('az')

  useEffect(() => {
    const saved = localStorage.getItem('glamora_language') as Language
    if (saved && ['az', 'en', 'ru'].includes(saved)) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('glamora_language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] ?? translations['en'][key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
